-- MySQL Script generated by MySQL Workbench
-- 12/02/15 01:22:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema nom_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nom_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nom_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `nom_db` ;

-- -----------------------------------------------------
-- Table `nom_db`.`bucket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nom_db`.`bucket` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` VARCHAR(45) NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `description` BLOB NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nom_db`.`bucketlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nom_db`.`bucketlist` (
  `bucket_id` INT NOT NULL COMMENT '',
  `business_id` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`bucket_id` ASC, `business_id` ASC)  COMMENT '',
  CONSTRAINT `list_to_bucket`
    FOREIGN KEY (`bucket_id`)
    REFERENCES `nom_db`.`bucket` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
